apiVersion: apps/v1
kind: Deployment
metadata:
 name: intellipaat
spec:
 replicas: 3
 selector:
  matchLabels:
   app: intellipaat
 template:
  metadata:
   labels:
    app: intellipaat
  spec:
   containers:
   - name: mycont
     image: jatin765/intellipaat:latest
     ports:
     - containerPort: 80
      
---
apiVersion: v1
kind: Service
metadata:
 name: intellipaat-service
spec:
 type: LoadBalancer
 ports:
 - port: 80
   targetPort: 80
   protocol: tcp
 selector:
 - app: intellipaat
